---
title: "build_up_tutorial"
author: "Thomas Cooper"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#First, lets load libraries and functions required for the tutorial
library(tidyr)
library(ggplot2)
library(EVCO2)

```


```{r, warning=FALSE, message=FALSE}
#Lets first look at some real-world data. Lets load it in
data = example_data
#We want to convert to date time using POSIXct, as this is required for the implementation of the build up method
data[,1] = as.POSIXct(data$`Time(dd/mm/yyyy)`, format = "%j/%m/%Y %I:%M:%S %p")

#The first thing that must be done is to select regions of exponential growth. If this is not known, the exp_periods()
#function can be ran to estimate regions of exponential activity. This function has two required arguments. The first
#argument is the vector of times in POSIXct format. To avoid errors, ensure the passed time list inherits the POSIXct attribute. The second is the vector of CO2 values. The third argument, quant_cutoff, is not required. This argument ranges from 0 to 1 and represents how selective the algorithm is in choosing regions of exponential growth. 0 is the least selective, and 1 is the most selective. Default value is 0.9. 

periods = exp_periods(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`)

periods_3q = exp_periods(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, quant_cutoff = 0.75)

periods_half = exp_periods(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, quant_cutoff = 0.5)

periods_1q = exp_periods(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, quant_cutoff = 0.25)

periods_zero = exp_periods(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, quant_cutoff = 0)

#Lets look at how the outputs differ

periods
periods_3q
periods_half
periods_1q
periods_zero

#As the cutoff decreases, more and more regions will be tagged as exponential growth. However, at cutoff of 0,
#the entire time series data is considered to be an exponential region. Note that this algorithm does not necessarily
#capture the beginning and end of each region, but instead tries to obtain two points that occur within any given identified region. Interval P Size is required for some calculations in other functions.
```


```{r}
#Now, lets do an example for calculating the air exchange rate using row 3 from the periods data frame.
#We will assume the following parameters:

n = 5 #number of people
Gp = Gp_rate(16/24) #CO2 generation rate, L / min / person
room_volume = 226.6746 #meters cubed

#We also need to calculate:

C0 = data$`Carbon dioxide(ppm)`[periods[3,1]] #initial CO2 concentration
t0 = periods[3,4] #initial time
C1 = data$`Carbon dioxide(ppm)`[periods[3,2]] #final CO2 concentration
t1 = periods[3,5] #final time

#get our delta time value for the same indexes
delta_t = as.numeric(difftime(t1,t0), units = "hours") #time difference

#Now, we need to determine the starting points for the secant method. We can do this by calling build_up_starter().
#We input NA for the variable we want to estimate, and fill in the rest of the arguments. By default Cr, the replacement air CO2 concentration, is 400.

bus_output = build_up_starter(aer = NA, n = n, Gp = Gp, V = room_volume, C0 = C0, C1 = C1, delta_t, Cr = 400)

#Lets display the output
cat('build_up_starter output \n')
bus_output
cat('---------------------------\n')

#Start and Stop are the two starting values to be input into the secant method algorithm to solve for the root of the build_up() equation. Asymptote is the location of the asymptote of the function, and is returned as diagnostic information.

#Now that we have our initial starting points, we can solve using the secant method! To do this we call the
#bulid_up_method function. Note that this function will call build_up_starter inside of it, so we do not have to
#pass that information to the function. tol and max_iter determine convergence tolerance and maximum number of iterations
#for the method to attempt.

bum_output = build_up_method(aer = NA, n = n, Gp = Gp, V = room_volume, C0 = C0, C1 = C1, delta_t, Cr = 400, tol=1e-10, max_iter=1000)

#Lets display the output
cat('build_up_method output \n')
bum_output
cat('---------------------------\n')

#The root value that is returned is the estimated value of the air exchange rate. f_root is the value of the build up
#method at root. iter returns the number of iterations before convergence. convergence is either a value of 0 or 1. 0 indicates that convergence was achieved. 1 indicates that convergence was not achieved within the maximum number of iterations.

#What is important to note is that this method can be used to estimate the other parameters! Lets input our estimated
#air exchange rate back into the method and try and re-estimate known parameters.

aer_est = bum_output$root

n_est = build_up_method(aer = aer_est, n = NA, Gp = Gp, V = room_volume, C0 = C0, C1 = C1, delta_t, Cr = 400, tol=1e-10, max_iter=1000)$root

Gp_est = build_up_method(aer = aer_est, n = n, Gp = NA, V = room_volume, C0 = C0, C1 = C1, delta_t, Cr = 400, tol=1e-10, max_iter=1000)$root

V_est = build_up_method(aer = aer_est, n = n, Gp = Gp, V = NA, C0 = C0, C1 = C1, delta_t, Cr = 400, tol=1e-10, max_iter=1000)$root

#Lets see if we get back our initial values!

cat("n estimate = ", n_est, "\n", 
    "Gp estimate = ", Gp_est, "\n",
    "Volume estimate = ", V_est, "\n",sep = "")
cat("\nn initial = ", n, "\n", 
    "Gp initial = ", Gp, "\n",
    "Volume initial = ", room_volume, "\n",sep = "")

#As one would expect, we obtain our initial parameters back when estimating with our calculated air exchange rate
```


```{r}
#Now that we know how the secant method works for solving the build_up() equation, lets look at how the build_up_main function works. This method will calculate estimates for every exponential growth period determined by the exp_periods() function. However, we need to obtain the times at which people are and are not in the room. We will assume that there are 5 individuals in the room between 9am and 5pm, and that there are 0 people in the room otherwise.

n_change = c(data$`Time(dd/mm/yyyy)`[1],
             as.POSIXct("13/11/2023 5:00:00 PM", format = "%j/%m/%Y %I:%M:%S %p", tz = 'est'),
             as.POSIXct("14/11/2023 9:00:00 AM", format = "%j/%m/%Y %I:%M:%S %p", tz = 'est'),
             as.POSIXct("14/11/2023 5:00:00 PM", format = "%j/%m/%Y %I:%M:%S %p", tz = 'est'),
             as.POSIXct("15/11/2023 9:00:00 AM", format = "%j/%m/%Y %I:%M:%S %p", tz = 'est'),
             as.POSIXct("15/11/2023 5:00:00 PM", format = "%j/%m/%Y %I:%M:%S %p", tz = 'est'))

#We will have to change the input argument of our n value. Because n changes over time, we must input n as a matrix.
#For other parameters, if they change over time, their format may vary. See the documentation of build_up_main for more information. Additionally, build_up_main will return error messages / warnings when data is input incorrectly.

n_mat = matrix(c(5,0,5,0,5,0),6,1)


bumain_output = build_up_main(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, aer = NA, n = n_mat, Gp = rep(Gp,6), V = rep(room_volume,6), n_change = n_change, quant_cutoff = 0.9, Cr = 400, tol=1e-10, max_iter=1000)

bumain_output

#Notice that some warning outputs were generated. This occurs whenever a period had to be skipped due to computation errors.
#All skipped periods are placed into removed_periods. Other return values give estimates either using raw or p-interval averaged CO2 values. The data frames contain more diagnostic data related to the entirety of the methods used for calculation.


#We can additionally use this function to estimate other parameters as well! We can do as we have done previously:

bumain_output_n = build_up_main(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, aer = aer_est, n = NA, Gp = Gp, V = room_volume, n_change = n_change, quant_cutoff = 0.9, Cr = 400, tol=1e-10, max_iter=1000)

bumain_output_Gp = build_up_main(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, aer = rep(aer_est,6), n = n_mat, Gp = NA, V = rep(room_volume,6), n_change = n_change, quant_cutoff = 0.9, Cr = 400, tol=1e-10, max_iter=1000)

bumain_output_V = build_up_main(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, aer = rep(aer_est,6), n = n_mat, Gp = rep(Gp,6), V = NA, n_change = n_change, quant_cutoff = 0.9, Cr = 400, tol=1e-10, max_iter=1000)

#Lets create some separations between our outputs to console

cat("\n------------------------------------------------------------------------------------\n")
bumain_output_n
cat("\n------------------------------------------------------------------------------------\n")
bumain_output_Gp
cat("\n------------------------------------------------------------------------------------\n")
bumain_output_V


#Every 4 data frames come from the same build_up_main output. The order is: aer, n, Gp, V estimates. Note that there
#is variability in the n estimate. This is because if we don't know the number of individuals in the room, then n_change will be ignored, and now these previously removed periods will have non-zero inputs for non-estimated parameters.
```


```{r}
#To no suprise, we can also use these methods on simulated data!

#Lets simulate some data



#Lets prepare for our build_up_method() function call

sim_bumain_output = build_up_main(simdat$POSIXtime, simdat$CO2, aer = NA, n = n_mat, Gp = rep(Gp,6), V = rep(room_volume,6), n_change = n_change, quant_cutoff = 0.9, Cr = 400, tol=1e-10, max_iter=1000)

sim_bumain_output
```







